= Step 04 : Adding a Database
:source-highlighter: coderay
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Summary

Let's add Persistence to our application.  The section will introduce the Vertx JDBC client and FlyWay.  Flyway isn't a Red Hat tool, but it is incredibly useful and should be part of every developer's toolkit.

== KeyTerms in this Step

* Flyway database migration tool: https://flywaydb.org
* HyperSQL http://hsqldb.org/

* io.vertx.ext.auth.AuthProvider
* io.vertx.ext.auth.jdbc.JDBCAuth
* io.vertx.ext.jdbc.JDBCClient

=== Flyway Database Migration Tool

Flyway is, "version control for your database," and makes dabase migrations (changes) simple.  If you have ever used Ruby on Rails you are familiar with the concept of database migrations.

Flyway has a command line interface, a Java API for use inside of your classes, and a Maven plugin.  We will start with the Java API to create and populate our database before we run our tests.

You can find the Flyway dependency on line 123 of your pom.xml:

[code,xml]
....

    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
      <version>${flyway.version}</version>
      <scope>test</scope>
    </dependency>

....

=== HSQLDB

HyperSQL database is a tiny, lightweight database that can be run completely in memory, which is great for testing.  It can also persist data to the filesyste.  It is another great tool to have in your toolkit.

The dependency can be found on line 106 of your pom.xml
[code,xml]
....

    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <version>${hsqldb.version}</version>
    </dependency>

....

Most of the configuration can be passed in the JDBC url.  For example, our url contains 2 important configuration parameters:

[code,xml]
....

jdbc:hsqldb:mem:rhte;db_close_delay=-1  <1> <2>

....

jdbc:hsqldb:mem:rhte;db_close_delay=-1
<1> "mem" tells HyperSQL to store data in memory only instead of writing anything to disk
<2> The "db_close_delay=-1" parameter tells Flyway not to exit if the initializing thread exits.  This is extremely important in Vert.x' world because the initializing thread will most likely disappear before the application is done with the database

== Step 1: Fail a test

Create a new test, "io.starter.vertx.database.DbVerticleTest."  Be sure to annotate it with the VertxUnitRunner, create a Vertx member variable, and "setUp" and "tearDown" methods:

[code,java]
....

package io.vertx.starter.database;

import io.vertx.core.Vertx;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;
...

@RunWith(VertxUnitRunner.class)
public class DbVerticleTest {

  private Vertx vertx;

  @Before
  public void setUp(TestContext tc) {
    vertx.deployVerticle(DbVerticle.class.getName(), options, tc.asyncAssertSuccess());     <1>
  }

  @After
  public void tearDown(TestContext tc){
      vertx.close(tc.asyncAssertSuccess());
  }

....

<1> This method deploys our (currently non-existent) DbVerticle

=== Creating the Database

Create a folder "src/main/resources/db/migration" to match the configuration in our pom.xml.  Create a new file named "V1_\_create-insults-table.sql," in this directory.  Be sure to have 2 underscores between the V1 and the name of the migration.

We can craft a "create table" statement to capture the insult text:

[code,sql]
....

create table if not exists INSULTS (ID INT IDENTITY PRIMARY KEY,  BODY VARCHAR(255) NOT NULL);

....

Create a new file, "V1_\_create-insult-table.sql" in the folder "src/main/resources/db/migration" and add the above text.

We will also prime the database with a few results.  Create another migration file, "V1.1_\_insert-insults.sql" in the folder "src/main/resources/db/migration" and add the following text:

[code,sql]
....

insert into INSULTS(BODY) VALUES ('infectious devil-monk');
insert into INSULTS(BODY) VALUES ('mammering measle');
insert into INSULTS(BODY) VALUES ('tardy-gaited varlot');

....

NOTE: HyperSQL is case sensitive.  Objects are created in upper case by default so we will use all uppercase letters.  If you use lower case table and field names you will have to wrap them in quotes.

Now, run the migrations:

[code,shell]
....
mvn flyway:migrate
....

You should see something similar to the following:

[code,shell]
....

[INFO] --- flyway-maven-plugin:5.1.4:migrate (default-cli) @ vertx-conduit-starter ---
[INFO] Flyway Community Edition 5.1.4 by Boxfuse
[INFO] Database: jdbc:hsqldb:mem/rhte (HSQL Database Engine 2.3)
[INFO] Successfully validated 2 migrations (execution time 00:00.010s)
[INFO] Creating Schema History table: "PUBLIC"."flyway_schema_history"
[INFO] Current version of schema "PUBLIC": << Empty Schema >>
[INFO] Migrating schema "PUBLIC" to version 1 - create-user-table
[INFO] Migrating schema "PUBLIC" to version 1.1 - insert-user
[INFO] Successfully applied 2 migrations to schema "PUBLIC" (execution time 00:00.035s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

....

This created our user table (and a Flyway table that stores information about the migrations) and inserted the user from the documentation.

The migrations will run in sequential order so "V1" comes before "V1.1"

NOTE: If for some reason something goes wrong with a Flyway migration you need to run "mvn flyway:repair" before rerunning the migration.

== Step 2: Access the Database

We will use Vert.x JDBCClient to access our database.  JDBC is blocking by nature (very few databases have non-blocking implementations) so Vert.x JDBCClient provides an asynchronous API on top of JDBC.

The JDBCClient module can be found on line 51 of your pom.xml
[code,xml]
....

<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-jdbc-client</artifactId>
</dependency>

....

You will need to add it to your DatabaseVerticle like so:

[code,java]
....

import io.vertx.ext.jdbc.JDBCClient;
...

  private JDBCClient jdbcClient;

....

Initialize the classes inside of DatabseVerticle's start method before the Router is initialized and configured:

[souce,java]
....
    jdbcClient = JDBCClient.createShared(vertx, new JsonObject()     <1>
      .put("url", "jdbc:hsqldb:file:db/rhte;shutdown=true")     <2>
      .put("driver_class", "org.hsqldb.jdbcDriver")     <3>
      .put("max_pool_size", 30));     <4>

    authProvider = JDBCAuth.create(vertx, jdbcClient);     <5>
    authProvider.setAuthenticationQuery("SELECT PASSWORD, PASSWORD_SALT FROM USER WHERE EMAIL = ?");     <6>
....

<1>  We instantiate the JDBCClient with the "createShared" method.  This will create a single instance that can be shared across Verticles.  We pass in the vertx member variable and a JsonObject for configuration.  Using Json for configuration is the default Vert.x approach.
<2>  The connection url points to the location where we will keep our database.  Flyway will create the "db" folder if it doesn't exist.  It's perfectly fine to keep the database in the project's root directory, but you might want to add "db/" to your .gitignore file.
<3>  We add the appropriate JDBC driver to the configuration.
<4>  This isn't terribly important in development, but we set the connection pool size anyway.
<5>  We instantiate the JDBCAuth AuthProvider with the vertx member variable and the JDBCClient we just created.
<6>  JDBCAuth expects us to authenticate against the "user" and "password" fields.  Our API, however, uses "email" and "password" so we are overriding the default query with one checks the "EMAIL" column instead of the "USER" column.

IMPORTANT: Read 6 above

Delete (or comment out) the stubbed out functionality in the loginHandler method because its time to build the real method.

The first step is to grab the user from the Json posted to our endpoint.

Json:
[code,json]
....
{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}
....

Code that pulls the user from the post:
[code,java]
....
    JsonObject user = context.getBodyAsJson().getJsonObject("user");
    JsonObject authInfo = new JsonObject()
      .put("username", user.getString("email"))     <1>
      .put("password", user.getString("password"));
....

<1>  Vert.x' JDBCAuth expects a parameter, "username," but we only have, "email."  Because of this we updated the query to pull from email, and we are passing in the supplied email with the key, "username."  This is just a workaround.

NOTE: There is an easier way to get Json from a request.  We will get to that shortly.

== Step 3: Authenticate Against the Database

[code,java]
....
    HttpServerResponse response = context.response();     <1>

    authProvider.authenticate(authInfo, ar -> {     <2>
      if (ar.succeeded()) {     <3>
        JsonObject returnValue = new JsonObject()     <4>
        .put("user", new JsonObject()
          .put("email", "jake@jake.jake")
          .put("password", "jakejake")
          .put("token", "jwt.token.here")
          .put("username", "jake")
          .put("bio", "I work at statefarm")
          .put("image", ""));

        response.setStatusCode(200)
        .putHeader("Content-Type", "application/json; charset=utf-8")
        .putHeader("Content-Length", String.valueOf(returnValue.toString().length()))
        .end(returnValue.encode());     <5>
      }else{
        response.setStatusCode(200)
          .putHeader("Content-Type", "text/html")
          .end("Authentication Failed: " + ar.cause());
      }
    });
....

<1>  Create an HttpServerResponse for obvious reasons
<2>  This method call, "authProvider.authenticate," does all of the work.  We pass in the authentication info from the request and a lambda to handle success or failure.
<3>  If the user is authenticated we stub out the response becaue we aren't pulling the entire user from the database yet.
<4>  Create a JsonObject and stub it out with expected values.
<5>  JsonObject.encode() encodes the JsonObject as a String.

The complete method is below so that you can check against it:

[code,java]
....
  private void loginHandler(RoutingContext context) {
    JsonObject user = context.getBodyAsJson().getJsonObject("user");
    user.put("username", "placeholder");

    JsonObject authInfo = new JsonObject()
      .put("username", user.getString("email"))
      .put("password", user.getString("password"));
    System.out.println(user);

    HttpServerResponse response = context.response();

    authProvider.authenticate(authInfo, ar -> {
      if (ar.succeeded()) {

        JsonObject returnValue = new JsonObject()
          .put("user", new JsonObject()
            .put("email", "jake@jake.jake")
            .put("password", "jakejake")
            .put("token", "jwt.token.here")
            .put("username", "jake")
            .put("bio", "I work at statefarm")
            .put("image", ""));
        System.out.println(returnValue);

        response.setStatusCode(200)
          .putHeader("Content-Type", "application/json; charset=utf-8")
          .putHeader("Content-Length", String.valueOf(returnValue.toString().length()))
          .end(returnValue.encode());
      }else{
        response.setStatusCode(200)
          .putHeader("Content-Type", "text/html")
          .end("Authentication Failed: " + ar.cause());
      }
    });
  }
....

=== Verify with the MainVerticleTest

[code,shell]
....
mvn clean test
....

It should pass.

== Step 4: Get the User Information from the Database and Return It

Remove the stubbed out "put" methods of our JsonObject "returnValue" so that we have room to work:

[code,java]
....
    authProvider.authenticate(authInfo, ar -> {
      if (ar.succeeded()) {

        JsonObject returnValue = new JsonObject();

        response.setStatusCode(200)
          .putHeader("Content-Type", "application/json; charset=utf-8")
          .putHeader("Content-Length", String.valueOf(returnValue.toString().length()))
          .end(returnValue.encode());
      }else{
        response.setStatusCode(200)
          .putHeader("Content-Type", "text/html")
          .end("Authentication Failed: " + ar.cause());
      }
    });
....

It's probably not a bad idea to run our tests again as a sanity check to make sure the tests are executing correctly.

[code,shell]
....
mvn clean test
....

Should produce failing tests.


