= Lab 06 : Service Discovery
:source-highlighter: coderay


In the previos lab, Our InsultGatewayService read the locations (urls) of the other 3 rest services (noun, adjective, adjective) from the configuration file. These services were running in aws ocp environment. In this session we will change the services URLS to services that are running inside our OCP cluster. 

To do that, we are going to use  ConfigMap that we used in our last lad  to point the urls to the services running inside openshift. 



=== What is Service Discovery in ?


Lets look at how Openshift and Kubernetes handles the discovery of microservices. To brief below are the few main components in OpenShift 

Pods - An addressable wrapper of one or more Docker containers
Replication Controllers - Used to define how many pods are always running in our cluster
Services - Allow us to define a service endpoint that is addressable throughout the cluster

The important piece here is the Kubernetes Service (having this called a service is annoying as we overload the word service a lot!). 

==== What is a Service?

A Service is a kubernetes abstraction to provide a network connection to one or more pods. For more detail see the background on how services work.

A service uses a label selector to find all the pods running which provide a certain network service on a port. You can add labels to a pod which are just a set of key/value pairs. Then a selector is just a set of key/value pairs used to match pods which have those same key/value pairs.

Each service is given its own IP address and port which remains constant for the lifetime of the service. So to access the service from inside your application or container you just bind to the IP address and port number for the service.

Note make sure the services are created before any of your pods which use them; otherwise the service won't have its IP address defined and you'll have to restart those pods.

At a high level, a Service serves as an internal load balancer. It identifies a set of replicated pods in order to proxy the connections it receives to them. Backing pods can be added to or removed from a Service arbitrarily while the Service remains consistently available, enabling anything that depends on the Service to refer to it at a consistent internal address.

==== Discovering services from your application


The simplest way to discover things inside Kubernetes is via DNS which does not require any custom client side code, dependency injection or magic libraries. It also benefits from working with all programming languages and frameworks!

Service discovery via DNS

In our example,  for a service with springbooot-noun  you can just hard code the host name springbooot-nounr in your application code but we are going to use configmap tha we created in the last session to point the urls to services running inside the openshift.

We are going to change service address for all the 3 services in the configmap .

==== Edit configmap-  insult-config
[code,script]
....
oc edit configmap insult-config -o yaml
....

We are changing the service address of the 3 services to the services running the cluster.

[code,script]
....
gateway.host.springboot.noun
gateway.host.springboot.noun.port
gateway.host.wildfly-swarm.adj
gateway.host.wildfly-swarm.adj.port
gateway.host.vertx.adj
gateway.host.vertx.adj.port
....

Here is the final configmap. Please make sure to  substitute the userid with your lab provided userid and guid.

[code,json]
....
"env": "local",
	"insults.address": "insults-address",
	"db.url": "jdbc:hsqldb:mem:testdb;shutdown=true",
	"db.driver": "org.hsqldb.jdbcDriver",
	"db.user": "sa",
	"db.password": "sa",
	"query.all-insults": "SELECT * FROM INSULTS",
	"gateway.circuit-timeout": 1000,
	"gateway.reset-timeout": 1000,
	"gateway.host.springboot.noun": "springboot-noun-service.devenv-{youruserid}.svc",
	"gateway.host.springboot.noun.port": 8080,
	"gateway.host.wildfly-swarm.adj": "wildflyswarm-adj.devenv-{youruserid}.svc",
	"gateway.host.wildfly-swarm.adj.port": 8080,
	"gateway.host.vertx.adj": "vertx-adjective-service.devenv-{youruserid}.svc",
	"gateway.host.vertx.adj.port": 8080
....


If you notice the hostname for all the three services are pointing to the kubernetes services. 



=== Deploy to openshift



1. Checkin your code to github

    git add.
    git commit -m "lab5" 
    git push 

2. Go to OCP console -> pipelines-{userid} project - > builds ->pipelines

3. click on vertx-insult-gateway-pipeline
4. Hit ' Start Pipe line'


Note: ConfigMap changes are automatically detected if we are using vertx-config-kubernetes-configmap module.


Example  way to use it. 

[code,source]
....
ConfigStoreOptions defaultConfig = new ConfigStoreOptions()
			      .setType("configmap")
			      .setFormat("json")
			      .setOptional(true)
		      .setConfig(new JsonObject().put("path", "conf/insult-config.json"));
....

Notice the type is set to configmap. 

More reading on using Kubernetes configmap:

https://vertx.io/docs/vertx-config/java/#_kubernetes_configmap_store

https://github.com/InfoSec812/vertx-configmap-example



Continue to Lab 7 -> https://github.com/rhte-reactive-labs/reactive-pipelines/blob/master/labs/lab07-CircuitBreaker.adoc











