
= Lab 07 : CircuitBreaker
:source-highlighter: coderay

In this lab we are going to learn about CircuitBreaker and how to apply to our use case.


A circuit breaker is an object monitoring an interaction, for instance the calls between our proxy and the flaky service. It starts in the closed state. In this state, the circuit breaker forward the calls to the service and monitor the outcome (successes or failures). When the circuit breaker reaches an amount of failure, it switches to the open state. In this state, the service is not called anymore, but a fallback response is used. After some specific time, the circuit breaker goes to the half-open state and let the next request pass and hit the service. Depending on the result of this request, the circuit breaker goes back to the open state (on failure) or the closed state (on success).


A circuit breaker is a great way to protect your system against flaky service and also gives them time to recover when they start failing (open state). When the service is back on track, and thanks to the half-open state, your system is going to auto-recover and restart using the service.

We will change our webclients in our previous labs use circuit breaker module. 

=== Vert.x Circuit Breaker

is an implementation of the Circuit Breaker pattern for Vert.x.

It keeps track of the number of failures and opens the circuit when a threshold is reached. Optionally, a fallback is executed.

Supported failures are:

failures reported by your code in a Future

exception thrown by your code

uncompleted futures (timeout)

Operations guarded by a circuit breaker are intended to be non-blocking and asynchronous in order to benefit from the Vert.x execution model.




=== 
=== Using the vert.x circuit breaker

Add the following the dependencies to your pom.xml

[code, xml]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-circuit-breaker</artifactId>
  <version>3.5.4</version>
</dependency>
----



=== Edit src/main/java/io/vert.x/starter/InsultGatewayVerticle.java 

Define the circuitbreaker config opts and import the class 

[code,java]
----

We are going to add below circuitbreaker options..


CircuitBreakerOptions breakerOpts = new CircuitBreakerOptions() 
			      .setFallbackOnFailure(true)
			      .setMaxFailures(2)
			      .setMaxRetries(2)
			      .setResetTimeout(config().getInteger(GATEWAY_CIRCUIT_TIMEOUT, 1000))
			      .setTimeout(config().getInteger(GATEWAY_RESET_TIMEOUT, 1000));
		
		
----

[code,java]
----
package io.vertx.starter;

import io.vertx.core.Future;
import io.vertx.core.AsyncResult;
import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.reactivex.core.http.HttpServerResponse;
import io.vertx.reactivex.ext.web.Router;
import io.vertx.reactivex.ext.web.RoutingContext;
import io.vertx.reactivex.ext.web.handler.StaticHandler;
import io.vertx.reactivex.config.ConfigRetriever;
import io.vertx.reactivex.ext.web.client.WebClient;
import io.vertx.ext.web.client.WebClientOptions;
import io.vertx.core.json.JsonObject;
import io.vertx.reactivex.ext.web.client.HttpResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.vertx.core.json.JsonArray;
import io.vertx.core.CompositeFuture;
import io.vertx.circuitbreaker.CircuitBreakerOptions;
import static io.vertx.starter.ApplicationProperties.*;

public class InsultGatewayVerticle extends AbstractVerticle{
	private static final Logger LOG = LoggerFactory.getLogger(InsultGatewayVerticle.class);

	private WebClient clientSpringboot;
    private WebClient clientSwarm;
    private WebClient clientVertx;
    private ConfigRetriever conf;

	@Override
	  public void start(Future<Void> startFuture) {

		conf = ConfigRetriever.create(vertx);
		Router router = Router.router(vertx);


		
		CircuitBreakerOptions breakerOpts = new CircuitBreakerOptions() 
			      .setFallbackOnFailure(true)
			      .setMaxFailures(2)
			      .setMaxRetries(2)
			      .setResetTimeout(config().getInteger(GATEWAY_CIRCUIT_TIMEOUT, 1000))
			      .setTimeout(config().getInteger(GATEWAY_RESET_TIMEOUT, 1000));
		
		

	    clientSpringboot = WebClient.create(vertx, new WebClientOptions()
	    	      .setDefaultHost(config().getString(GATEWAY_HOST_SPRINGBOOT_NOUN, "springboot-noun-service-devenv-user2.apps.9249.rhte.opentlc.com")) 
	    	      .setDefaultPort(config().getInteger(GATEWAY_HOST_SPRINGBOOT_NOUN_PORT, 80)));

	    	    clientSwarm = WebClient.create(vertx, new WebClientOptions()
	    	      .setDefaultHost(config().getString(GATEWAY_HOST_WILDFLYSWARM_ADJ, "wildflyswarm-adj-devenv-user2.apps.9249.rhte.opentlc.com"))
	    	      .setDefaultPort(config().getInteger(GATEWAY_HOST_WILDFLYSWARM_ADJ_PORT, 80))); 



	    	    clientVertx = WebClient.create(vertx, new WebClientOptions()
	    	            .setDefaultHost(config().getString(GATEWAY_HOST_VERTX_ADJ,"vertx-adjective-service-devenv-user2.apps.9249.rhte.opentlc.com"))
	    	            .setDefaultPort(config().getInteger(GATEWAY_HOST_VERTX_ADJ_PORT,80))); 
	    	    
	    	    
	    	    
	    	    System.out.println("GATEWAY_HOST_WILDFLYSWARM_ADJ="+config().getString(GATEWAY_HOST_VERTX_ADJ,"springboot-noun-service.vertx-adjective.svc"));
	    	    System.out.println("GATEWAY_HOST_SPRINGBOOT_NOUN="+config().getString(GATEWAY_HOST_SPRINGBOOT_NOUN,"wildflyswarm-adj.vertx-adjective.svc"));
	    	    System.out.println("GATEWAY_HOST_VERTX_ADJ="+config().getString(GATEWAY_HOST_VERTX_ADJ,"wildflyswarm-adj.vertx-adjective.svc"));
	    	    
	    	    

	    	    vertx.createHttpServer().requestHandler(router::accept).listen(8080);
	    	    router.get("/api/insult").handler(this::insultHandler);
	    	    router.get("/*").handler(StaticHandler.create());


	    startFuture.complete();


	}
	Future<JsonObject> getNoun() {    
        Future<JsonObject> fut = Future.future();
        clientSpringboot.get("/api/noun")
                .timeout(3000)
                .rxSend()  

                .map(HttpResponse::bodyAsJsonObject) 
                .doOnError(fut::fail)
                .subscribe(fut::complete);
        return fut;
    }


	Future<JsonObject> getAdjective() {
        Future<JsonObject> fut = Future.future();
        clientSwarm.get("/api/adjective")
                .timeout(3000)
                .rxSend()

                .map(HttpResponse::bodyAsJsonObject)
                .doOnError(fut::fail)
                .subscribe(fut::complete);
        return fut;
    }
	Future<JsonObject> getAdjective2() {
        Future<JsonObject> fut = Future.future();
        clientVertx.get("/api/adjective")
                .timeout(3000)
                .rxSend()

                .map(HttpResponse::bodyAsJsonObject)
                .doOnError(fut::fail)
                .subscribe(fut::complete);
        return fut;
    }
	private AsyncResult<JsonObject> buildInsult(CompositeFuture cf) { 
        JsonObject insult = new JsonObject();
        JsonArray adjectives = new JsonArray();

        // Because there is no garanteed order of the returned futures, we need to parse the results

        for (int i=0; i<=cf.size()-1; i++) {
        	 JsonObject item = cf.resultAt(i);
             if (item.containsKey("adjective")) {
                 adjectives.add(item.getString("adjective"));
             } else {
                 insult.put("noun", item.getString("noun"));
             }

        }
        insult.put("adjectives", adjectives);


        return Future.succeededFuture(insult);
    }
	private void insultHandler(RoutingContext rc) {

		CompositeFuture.all(getNoun(), getAdjective(), getAdjective2()) 
        .setHandler(ar -> {

        	if (ar.succeeded()) {
        		AsyncResult<JsonObject> result=buildInsult(ar.result());
        		 rc.response().putHeader("content-type", "application/json").end(result.result().encodePrettily());
        	}
        	else
        	{
        		System.out.println("error");

        		rc.response().putHeader("content-type", "application/json").end(new JsonObject("Error").encodePrettily());
        	}



          });
	  }

	}
----


In the above code, we are configuring the circuitbreaker with options like timeout, retries, failures etc.



=== Initialize the cicrcuit breker objects


[code,java]
----
clientSpringbootBreaker = CircuitBreaker
      .create("nounSpringBoot", vertx, breakerOpts)
      .openHandler(t -> circuitBreakerHandler("adj", "[open]"));


    clientSwarmBreaker = CircuitBreaker
      .create("swarmAdj", vertx, breakerOpts)
      .openHandler(t -> circuitBreakerHandler("swarmAdj", "[open]"));


    clientVertxBreaker = CircuitBreaker
      .create("vertxAdj", vertx, breakerOpts)
      .openHandler(t -> circuitBreakerHandler("vertxAdj", "[open]"));
----

Here is the class after adding above code


[code,java]
----
package io.vertx.starter;

import io.vertx.core.Future;
import io.vertx.core.AsyncResult;
import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.reactivex.core.http.HttpServerResponse;
import io.vertx.reactivex.ext.web.Router;
import io.vertx.reactivex.ext.web.RoutingContext;
import io.vertx.reactivex.ext.web.handler.StaticHandler;
import io.vertx.reactivex.config.ConfigRetriever;
import io.vertx.reactivex.ext.web.client.WebClient;
import io.vertx.ext.web.client.WebClientOptions;
import io.vertx.core.json.JsonObject;
import io.vertx.reactivex.ext.web.client.HttpResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import io.vertx.core.json.JsonArray;
import io.vertx.core.CompositeFuture;
import io.vertx.circuitbreaker.CircuitBreakerOptions;
import static io.vertx.starter.ApplicationProperties.*;
import io.vertx.reactivex.circuitbreaker.CircuitBreaker;
import io.vertx.circuitbreaker.CircuitBreakerOptions;


public class InsultGatewayVerticle extends AbstractVerticle{
	private static final Logger LOG = LoggerFactory.getLogger(InsultGatewayVerticle.class);

	private WebClient clientSpringboot;
    private WebClient clientSwarm;
    private WebClient clientVertx;
    private ConfigRetriever conf;
    
    CircuitBreaker clientSpringbootBreaker;
    CircuitBreaker clientSwarmBreaker;
    CircuitBreaker clientVertxBreaker;
    
    

	@Override
	  public void start(Future<Void> startFuture) {

		conf = ConfigRetriever.create(vertx);
		Router router = Router.router(vertx);


		
		CircuitBreakerOptions breakerOpts = new CircuitBreakerOptions()
			      .setFallbackOnFailure(true)
			      .setMaxFailures(2)
			      .setMaxRetries(2)
			      .setResetTimeout(config().getInteger(GATEWAY_CIRCUIT_TIMEOUT, 1000))
			      .setTimeout(config().getInteger(GATEWAY_RESET_TIMEOUT, 1000));
		
		clientSpringbootBreaker = CircuitBreaker
			      .create("nounSpringBoot", vertx, breakerOpts)
			      .openHandler(t -> circuitBreakerHandler("adj", "[open]"));


			    clientSwarmBreaker = CircuitBreaker
			      .create("swarmAdj", vertx, breakerOpts)
			      .openHandler(t -> circuitBreakerHandler("swarmAdj", "[open]"));


			    clientVertxBreaker = CircuitBreaker
			      .create("vertxAdj", vertx, breakerOpts)
			      .openHandler(t -> circuitBreakerHandler("vertxAdj", "[open]"));
		

	    clientSpringboot = WebClient.create(vertx, new WebClientOptions()
	    	      .setDefaultHost(config().getString(GATEWAY_HOST_SPRINGBOOT_NOUN, "springboot-noun-service-devenv-user2.apps.9249.rhte.opentlc.com")) 
	    	      .setDefaultPort(config().getInteger(GATEWAY_HOST_SPRINGBOOT_NOUN_PORT, 80)));

	    	    clientSwarm = WebClient.create(vertx, new WebClientOptions()
	    	      .setDefaultHost(config().getString(GATEWAY_HOST_WILDFLYSWARM_ADJ, "wildflyswarm-adj-devenv-user2.apps.9249.rhte.opentlc.com"))
	    	      .setDefaultPort(config().getInteger(GATEWAY_HOST_WILDFLYSWARM_ADJ_PORT, 80))); 



	    	    clientVertx = WebClient.create(vertx, new WebClientOptions()
	    	            .setDefaultHost(config().getString(GATEWAY_HOST_VERTX_ADJ,"vertx-adjective-service-devenv-user2.apps.9249.rhte.opentlc.com"))
	    	            .setDefaultPort(config().getInteger(GATEWAY_HOST_VERTX_ADJ_PORT,80))); 
	    	    
	    	    
	    	    
	    	    System.out.println("GATEWAY_HOST_WILDFLYSWARM_ADJ="+config().getString(GATEWAY_HOST_VERTX_ADJ,"springboot-noun-service.vertx-adjective.svc"));
	    	    System.out.println("GATEWAY_HOST_SPRINGBOOT_NOUN="+config().getString(GATEWAY_HOST_SPRINGBOOT_NOUN,"wildflyswarm-adj.vertx-adjective.svc"));
	    	    System.out.println("GATEWAY_HOST_VERTX_ADJ="+config().getString(GATEWAY_HOST_VERTX_ADJ,"wildflyswarm-adj.vertx-adjective.svc"));
	    	    
	    	    

	    	    vertx.createHttpServer().requestHandler(router::accept).listen(8080);
	    	    router.get("/api/insult").handler(this::insultHandler);
	    	    router.get("/*").handler(StaticHandler.create());


	    startFuture.complete();


	}
	Future<JsonObject> getNoun() {    
        Future<JsonObject> fut = Future.future();
        clientSpringboot.get("/api/noun")
                .timeout(3000)
                .rxSend()  

                .map(HttpResponse::bodyAsJsonObject) 
                .doOnError(fut::fail)
                .subscribe(fut::complete);
        return fut;
    }

	public JsonObject circuitBreakerHandler(String key, String value) {
	    System.out.println("Error= " + key + "," + "value=" + value);

	    return new JsonObject().put(key, value);
	  }
	Future<JsonObject> getAdjective() {
        Future<JsonObject> fut = Future.future();
        clientSwarm.get("/api/adjective")
                .timeout(3000)
                .rxSend()

                .map(HttpResponse::bodyAsJsonObject)
                .doOnError(fut::fail)
                .subscribe(fut::complete);
        return fut;
    }
	Future<JsonObject> getAdjective2() {
        Future<JsonObject> fut = Future.future();
        clientVertx.get("/api/adjective")
                .timeout(3000)
                .rxSend()

                .map(HttpResponse::bodyAsJsonObject)
                .doOnError(fut::fail)
                .subscribe(fut::complete);
        return fut;
    }
	private AsyncResult<JsonObject> buildInsult(CompositeFuture cf) { 
        JsonObject insult = new JsonObject();
        JsonArray adjectives = new JsonArray();

        // Because there is no garanteed order of the returned futures, we need to parse the results

        for (int i=0; i<=cf.size()-1; i++) {
        	 JsonObject item = cf.resultAt(i);
             if (item.containsKey("adjective")) {
                 adjectives.add(item.getString("adjective"));
             } else {
                 insult.put("noun", item.getString("noun"));
             }

        }
        insult.put("adjectives", adjectives);


        return Future.succeededFuture(insult);
    }
	private void insultHandler(RoutingContext rc) {

		CompositeFuture.all(getNoun(), getAdjective(), getAdjective2()) 
        .setHandler(ar -> {

        	if (ar.succeeded()) {
        		AsyncResult<JsonObject> result=buildInsult(ar.result());
        		 rc.response().putHeader("content-type", "application/json").end(result.result().encodePrettily());
        	}
        	else
        	{
        		System.out.println("error");

        		rc.response().putHeader("content-type", "application/json").end(new JsonObject("Error").encodePrettily());
        	}



          });
	  }

	}
----


In the above code, we are initializing our circuitbreaker , with the options we created early along with the handler to call when services are down. 



=== Replace the following three methods in the same class - src/main/java/io/vert.x/starter/InsultGatewayVerticle.java

[code,java]
----

import io.vertx.reactivex.circuitbreaker.CircuitBreaker; // import following classes
import io.vertx.circuitbreaker.CircuitBreakerOptions;
import io.vertx.reactivex.core.CompositeFuture;
.....
.....

  io.vertx.reactivex.core.Future<JsonObject> getNoun() {


    return clientSpringbootBreaker.executeWithFallback(fut ->
      clientSpringboot.get("/api/noun")
        .timeout(3000)
        .rxSend()
        .doOnError(e -> LOG.error("REST Request failed", e))
        .map(HttpResponse::bodyAsJsonObject)
        .subscribe(
          j -> fut.complete(j),
          e -> fut.fail(e)
        ), t -> circuitBreakerHandler("noun", "[SpringBoot noun failure]"));


    //eturn fut;
  }


  io.vertx.reactivex.core.Future<JsonObject> getAdjective() {


    return clientSwarmBreaker.executeWithFallback(fut ->
      clientSwarm.get("/api/adjective")
        .timeout(3000)
        .rxSend()
        .doOnError(e -> LOG.error("REST Request failed", e))
        .map(HttpResponse::bodyAsJsonObject)
        .subscribe(
          j -> fut.complete(j),
          e -> fut.fail(e)
        ), t -> circuitBreakerHandler("adjective", "[Swarm adjective failure]"));
  }

  io.vertx.reactivex.core.Future<JsonObject> getAdjective2() {
    return clientVertxBreaker.executeWithFallback(fut ->
      clientVertx.get("/api/adjective")
        .timeout(3000)
        .rxSend()
        .doOnError(e -> LOG.error("REST Request failed", e))
        .map(HttpResponse::bodyAsJsonObject)
        .subscribe(
          j -> fut.complete(j),
          e -> fut.fail(e)
        ), t -> circuitBreakerHandler("adjective", "[Vertx adj failure]"));
  }

----
We are wrapping our WebClient with a CircuitBreaker proxy API and registered a callback for catching failures and calling the fallback method ..in this case 'cicuitBreakerHandler' method.

Please make sure to import proper classes, especially following import

[source,java]
----
import io.vertx.reactivex.core.CompositeFuture;
----

And remove the original CompositeFuture import.

=== Build and deploy to openshift

Please make sure you are on oc project devenv-{username}



[code,script]
....
oc project devenv-{username}
mvn clean fabric8:deploy -Popenshift


INFO] F8: Using OpenShift at https://master.435b.rhte.opentlc.com:443/ in namespace devenv-user1 with manifest /Users/rmaddali/workshops/reactive/techexchange/vertx-insult-gateway/vertx-mvn-starter/vertx-insult-gateway/target/classes/META-INF/fabric8/openshift.yml
[INFO] OpenShift platform detected
[INFO] Using project: devenv-user1
Trying internal type for name:Service
Trying internal type for name:DeploymentConfig
Trying internal type for name:Route
[INFO] Updating a Service from openshift.yml
[INFO] Updated Service: target/fabric8/applyJson/devenv-user1/service-vertx-insult-gateway.json
[INFO] Using project: devenv-user1
[INFO] Updating DeploymentConfig from openshift.yml
[INFO] Updated DeploymentConfig: target/fabric8/applyJson/devenv-user1/deploymentconfig-vertx-insult-gateway.json
[INFO] F8: HINT: Use the command `oc get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.283 s
[INFO] Finished at: 2018-10-10T14:03:52-04:00
....


=== Testing CircuitBreaker


[code, script]
----
oc scale --replicas=0 dc/wildflyswarm-adj
----

Go to http://vertx-insult-gateway-devenv-{USERID}.apps.{GUID}.rhte.opentlc.com/api/insult

You should see following response

[code,json]
----
{
noun: "bum-bailey",
adjectives: [
"[Swarm adjective failure]",
"elf-skinned"
]
}
----

Notice in the response, you are seeing swarm adjective failures instead of the actual adjective.

Student TODO: Bring the same pod up again and check the message 


===  Circuit Breaker State

Lets implement some more functionality to know the status of circuit breaker


=== Edit src/main/java/io/vert.x/starter/InsultGatewayVerticle.java 

[code, java]
----
router.get("/api/cb-state").handler(this::checkHealth);
----
Here we are defining a new endpoint to get the status of the circuit breaker . Now, add a new method as below . Please make sure to import the class. 
[code, java]
----
 import io.vertx.circuitbreaker.CircuitBreakerState;
 .
 ...

public void checkHealth(RoutingContext rc) {
    // Request 2 adjectives and a noun in parallel, then handle the results


    boolean allBreakersClosed = (
      (clientSpringbootBreaker.state().equals(CircuitBreakerState.CLOSED)) &&
        (clientSwarmBreaker.state().equals(CircuitBreakerState.CLOSED)) && (clientVertxBreaker.state().equals(CircuitBreakerState.CLOSED)));


    JsonObject health = new JsonObject()
      .put("noun", new JsonObject()
        .put("failures", clientSpringbootBreaker.failureCount())
        .put("state", clientSpringbootBreaker.state().toString()))
      .put("Swarmadjective", new JsonObject()
        .put("failures", clientSwarmBreaker.failureCount())
        .put("state", clientSwarmBreaker.state().toString()))
      .put("Vertxadjective", new JsonObject()
        .put("failures", clientVertxBreaker.failureCount())
        .put("state", clientVertxBreaker.state().toString()))
      .put("status", allBreakersClosed ? "OK" : "UNHEALTHY");


    rc.response().putHeader("content-type", "application/json").end(health.encodePrettily());


  }

----

We added a new method called, checkHealth, which checks for state of the circuit breaker and build as json object as response

==== Deploy to openshift

Checkin your code to github

git add.
git commit -m "lab7"
git push
Go to OCP console → pipelines-{userid} project - > builds →pipelines

click on vertx-insult-gateway-pipeline

Hit ' Start Pipe line'




----

Check the following URL and you should below response 


http://vertx-insult-gateway-devenv-{USERID}.apps.{GUID}.rhte.opentlc.com/api/cb-state

[code, json]
....
{
noun: {
failures: 0,
state: "CLOSED"
},
Swarmadjective: {
failures: 0,
state: "CLOSED"
},
Vertxadjective: {
failures: 0,
state: "CLOSED"
},
status: "OK"
}
....



TODO : Play around with circuit breaker, shuting down the pods and bring them up and check the state of the circuit breaker as above. 

Continue to Lab 8 -> https://github.com/rhte-reactive-labs/reactive-pipelines/blob/master/labs/lab08-HealthChecks.adoc
