= Lab 02 : REST Basics with Vert.x-Web
:source-highlighter: prettify

== Key Terms in This Step
* Future<Void>
* Router
* RoutingContext

== Vert.x Core

Vert.x's core functionality contains an HTTP server.  The example app you cloned spins one up on port 8080 and returns a simple "Hello, Vert.x".   Open src/main/java/io/vertx/starter/MainVerticle.java :

[source,java]
....
package io.vertx.conduit;

import io.vertx.core.AbstractVerticle;

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start() {
    vertx.createHttpServer()
        .requestHandler(req -> req.response().end("Hello Vert.x!"))
        .listen(8080);
  }

}
....

We need more than a single endpoint saying, "Hello."

== Vert.x-Web

https://vertx.io/docs/vertx-web/java/


We will be using Vert.x-Web to build our endpoints.  

Vert.x-Web is one of many Vert.x modules that extend the core toolkit.  add the following dependency in your pom.xml. 

[source,xml]
....
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-web</artifactId>
</dependency>
....

Vert.x-Web is as a Swiss Army Knife for building modern, scalable, web apps.  Vert.x core provides a fairly low level set of functionality for handling HTTP, and for some applications that will be sufficient.  Vert.x-Web adds functionality for building real web applications and is especially awesome for building REST APIs and REST based microservices.

Vert.x-Web is influenced by Express in the NodeJS world and Sinatra in the Ruby world so if you have used either of those projects you will feel right at home. 

=== Vert.x-Web Router

Vert.x-Web contains a "Router" that maps URLs to Java methods.  Our initial code uses Vert.x's core HTTP server to return a single endpoint.  We will update our MainVerticle class to use the Vert.x-Web Router instead.

==== Future<Void>

The first thing we will do is to make sure that our Router is correctly set up and working when we start the application.  We will pass an io.vertx.core.Future Object to MainVerticle's start() method and call the complete() method once the Verticle is initialized and running.

WARNING: Your IDE will probably automatically import classes while you are typing.  Make sure that the imported classes are the one in the examples.  Your IDE may not grab the correct "Future."

[source,java]
....

package io.vertx.starter;

import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.core.Future;

public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Future<Void> startFuture) {  //          <1>
    vertx.createHttpServer()
        .requestHandler(req -> req.response().end("Hello Vert.x Insult Gateway!"))
        .listen(8080);

    startFuture.complete();  //          <2>
  }

}

....

<1>  We pass in a Vertx Future of type Void
<2>  We complete the Future object

In our next step we will check with our future to verify that the Router is working correctly.

==== Vert.x-Web Router

Now its time to add the Router to our start method just above the existing code and let the Router handle our url:

[source,java]
....
    
package io.vertx.starter;

import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.reactivex.ext.web.Router;  //          <1>

public class MainVerticle extends AbstractVerticle {

	@Override
	public void start(Future<Void> startFuture) {

		Router router = Router.router(vertx);  //          <2>
		router.route("/").handler(this::indexHandler);  //          <3> <4>

		vertx.createHttpServer().requestHandler(router::accept).listen(8080, result -> {  //          <5>
			if (result.succeeded()) {
				startFuture.complete();  //          <6>
			} else {
				startFuture.fail(result.cause());  //          <7>
			}
		});
	}

}

....

<1>  Import the Router from the "io.vertx.reactivex.ext.web" package.  Be sure to use this package.  There is another Router in the "io.vertx.ext.web" package; we don't want that one. we will working with reactive extensions the whole labs.
<2>  Instantiate the router
<3>  Assign the root endpoint, "/," to the Router
<4>  Attach a Vertx Handler the root endpoint, "/"
<5>  We pass a callback to the listen method that verifies our Router is working correctly.  We do this by telling our Future that we succeeded or failed
<6> future.complete() means we succeeded
<7> future.fail(result.cause()) means we failed and should throw an error


==== indexHandlder

Obviously, our code won't compile at the moment because we don't have a method, "indexHandler."  So let's create that method:

[source,java]
....

package io.vertx.starter;

import io.vertx.core.Future;
import io.vertx.reactivex.core.AbstractVerticle;
import io.vertx.reactivex.core.http.HttpServerResponse;  //          <1>
import io.vertx.reactivex.ext.web.Router;
import io.vertx.reactivex.ext.web.RoutingContext;  //          <2>

public class MainVerticle extends AbstractVerticle {

	@Override
	public void start(Future<Void> startFuture) {

		Router router = Router.router(vertx);
		router.route("/").handler(this::indexHandler);

		vertx.createHttpServer().requestHandler(router::accept).listen(8080, result -> {
			if (result.succeeded()) {
				startFuture.complete();
			} else {
				startFuture.fail(result.cause());
			}
		});
	}

	private void indexHandler(RoutingContext routingContext) {  //          <3>
		HttpServerResponse response = routingContext.response();  //          <4>
		response.putHeader("Content-Type", "text/html").end("Hello, Vert.x Insult Gateway!");  //          <5> <6>
	}
}

....


<1> Import the HttpServerResponse from the reactivex package
<2>  Import the RoutingContext form the reactivex package
<3>  We pass in an Object "RoutingContext" to our method.   A RoutingContext represents the context for the handling of a request in Vert.x-Web.  A new instance is created for each HTTP request that is received in the Router.accept(HttpServerRequest) of the router.  The same instance is passed to any matching request or failure handlers during the routing of the request or failure.  The context provides access to the HttpServerRequest and HttpServerResponse and allows you to maintain arbitrary data that lives for the lifetime of the context such as the Session, cookies and body for the request.  Contexts are discarded once they have been routed to the handler for the request.
<4>  We create the response
<5>  Set the Content-Type of our response
<6>  Set the body of our response

Let's run MainVerticleTest to make sure we didn't break anything.  You can use your IDE of course, but for the tutorial we will use Maven directly.

[source,shell]
....
mvn clean test
....

The test should fail of course because our text doesn't match.

[source,shell]
....
Running io.vertx.starter.MainVerticleTest
Oct 10, 2018 5:54:38 PM io.vertx.core.http.impl.HttpClientResponseImpl
SEVERE: java.lang.AssertionError: Expected true
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.788 sec <<< FAILURE!
testThatTheServerIsStarted(io.vertx.starter.MainVerticleTest)  Time elapsed: 0.739 sec  <<< FAILURE!
java.lang.AssertionError: Expected true
....

Update your test (or your Verticle) so that the test passes.  In case you run into any difficulty the solution is below:

[code,java]
....

package io.vertx.starter;

import io.vertx.core.Vertx;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(VertxUnitRunner.class)
public class MainVerticleTest {

  private Vertx vertx;

  @Before
  public void setUp(TestContext tc) {
    vertx = Vertx.vertx();
    vertx.deployVerticle(MainVerticle.class.getName(), tc.asyncAssertSuccess());
  }

  @After
  public void tearDown(TestContext tc) {
    vertx.close(tc.asyncAssertSuccess());
  }

  @Test
  public void testThatTheServerIsStarted(TestContext tc) {
    Async async = tc.async();
    vertx.createHttpClient().getNow(8080, "localhost", "/", response -> {
      tc.assertEquals(response.statusCode(), 200);
      response.bodyHandler(body -> {
        tc.assertTrue(body.length() > 0);
        tc.assertTrue(body.toString().equalsIgnoreCase("Hello, Vert.x Insult Gateway!"));  //          <1>
        async.complete();
      });
    });
  }

}

....

<1>  This is the text that should match

If you are encountering problems raise your hand and ask one of the proctors for help!


Continue to Lab 3 -> https://github.com/rhte-reactive-labs/reactive-pipelines/blob/master/labs/lab03-Restapi-InsultGateway.adoc

