= Lab 1 : Getting Started
:source-highlighter: coderay


== Fork the Vert.x Insult Gateway Starter Project
Got to the https://github.com/rhte-reactive-labs/vertx-insult-gateway
In the top-right corner of the page, click Fork

== Clone the Vert.x Insult Gateway Starter Project
[source,shell]
----
git clone https://github.com/{YOUR-REPO}/vertx-insult-gateway.git // (1)
----
* This is a basic Vert.x project that we will use as a starting point



=== A Few Things About Your pom.xml
Using the text editor of your choice open the pom.xml file.

[source,xml]
....
  <groupId>io.vertx.starter</groupId>    // (1)
  <artifactId>vertx-insult-gateway</artifactId>
  <version>1.0-SNAPSHOT</version>

  <properties>
    <vertx.version>3.5.2</vertx.version>     
    <main.verticle>io.vertx.starter.MainVerticle</main.verticle>     // (2)
  </properties>
....

<1> The starter project contains "Step 0" of this tutorial
<2> This class already exists.  It is where we will begin our work.  This property tells java which file in our fat jar should be run.

=== RX Java 
Open the pom.xml and take a look at the dependies. you would also notice Rxjava dependencies as we will be using RxJava for all this labs. 

RX Java is an implementation of the reactive programming principles for Java. With this development model, we manipulate streams (called Flowable, Observable, Maybe, Single or Completable depending on the number of items and their characteristics). RX Java provides a lots of operators to compose streams together and so write asynchronous orchestration easily. This exercise is a very basic introduction to RX Java.

=== IDE Time

==== Eclipse
==== IntelliJ



==== About
https://www.jetbrains.com/idea/

==== Creating a new project
1. Choose "File -> New -> Project From Existing Sources..."
2. Browse to the directory holding your project and choose the directory itself and choose "Open."  This will start an import wizard
3. "Maven" should already be selected in the "Import Project" dialog.  Click, "Next"
4. "Root Directory" should be highlighted with the directory of your project.  Click, "Next"
5. "redhat-jboss-ga" and "techpreview-all-repository" should already be selected.  Click, "Next"
6. "io.vertx.starter:vertx-insult-gateway:1.0-SNAPSHOT
7.  Be sure to select JDK 1.8.  Click, "Next"
8.  Project name should be "vertx-insult-gateway."  Click, "Finish"
9.  You can open the project in a new window or use your existing one

We will be using mvn directly for this tutorial.  You can run the following terminal commands in IntelliJ's Terminal window if you like.

==== Eclipse/JBoss Developer Studio
Import -> Existing Maven Project -> Browse

==== Visual Studio Code

== Real Work!

=== Build and test 

For simplicity's sake we will use maven to build and test.  You are welcome to use your IDE's mechanism if you prefer, but we recommend checking every now again with Maven on the command line just to be sure your IDE hasn't added something magical in the background. 

[source,shell]
....
cd vertx-insult-gateway
mvn clean package
....

You should successfully build and pass the default test.

Open up the "target" directory, and you will see 2 jar files.  We will be running our application from the "-fat.jar"

===  Verticles
While using a main method is nice and simple, it does not necessarily scale. When your code base grows, you need a better way to structure your code. For this, Vert.x provides verticles - a simple agent-like model. Verticles are single-threaded classes interacting using asynchronous messages.

=== Launch our first Verticle

This project includes a src/main/java/io/vertx/start/MainVerticle.java. Open the java file and take a look at it.

Now, Let's fire up our first verticle!


[source,shell]
....
java -jar ./target/vertx-insult-gateway-1.0-SNAPSHOT-fat.jar
....

You should see the following message:

[source,shell]
....
INFO: Succeeded in deploying verticle
....

Open http://localhost:8080  

You should see, "Hello, Vert.x!"

Ctrl + c to stop the server

=== Working on the Verticle

Open src/main/java/io/vertx/starter/MainVerticle.java

Change the "Hello, Vert.x" text to "Hello, Vert.x Insult Gateway"
Check your browser again.  You should see, "Hello, Vert.x Insult Gateway"

Stop your application with Ctrl + c

== Edit src/test/java/io/vertx/starter/MainVerticleTest.java

The vertx-insult-gateway project comes with a single Verticle, MainVerticle, and a single unit test, MainVerticleTest.  The complete class is annotated below, but open MainVerticleTest in your IDE (or editor) because we broke the test in the previous section, and it needs to be fixed.

=== Vert.x JUnit  Integration
https://vertx.io/preview/docs/vertx-junit5/java/

[code,java]
....
package io.vertx.starter;

import io.vertx.core.Vertx;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(VertxUnitRunner.class)
public class MainVerticleTest {

  private Vertx vertx;

  @Before
  public void setUp(TestContext tc) {
    vertx = Vertx.vertx(); <1>
    vertx.deployVerticle(MainVerticle.class.getName(), tc.asyncAssertSuccess()); // (2)
  }

  @After
  public void tearDown(TestContext tc) {
    vertx.close(tc.asyncAssertSuccess());
  }

  @Test
  public void testThatTheServerIsStarted(TestContext tc) { // (3)
    Async async = tc.async();
    vertx.createHttpClient().getNow(8080, "localhost", "/", response -> { // (4)
      tc.assertEquals(response.statusCode(), 200); <5>
      response.bodyHandler(body -> {
        tc.assertTrue(body.length() > 0);
        tc.assertTrue(body.toString().equalsIgnoreCase("Hello Vert.x!"));
        async.complete();
      });
    });
  }

}
....

<1>  We import and use a Vert.x object because we will spin up and run our Verticles within the unit test.  Vert.x is a toolkit unlike application servers or servlet containers.   we run it directly.
<2>   First, we deploy our Verticle from the test.  This gives us the ability to swap out components because we will eventually have more than one and control configuration from our unit tests.The second thing to notice is the callback, "testContext.succeeding."  VertxExtension to JUnit provides "failing" and "succeeding" callbacks


<3>  We pass a Vertx object and a VertxTestContext object to each test method.  These are supplied by the VertxExtension
<4>  We instantiate the WebCliet to test our endpoint
<5>  Async handler to for a callback when the response is ready and asserting on the response
<6>  Change this code to "Hello, Vert.x Insult Gateway!"

Rinse and repeat.  Your test should pass.  If it doesn't raise your hand and ask one of the guys proctoring the exam for help.

Continue to Lab 2 -> https://github.com/rhte-reactive-labs/reactive-pipelines/blob/master/labs/lab02-Vertx%20Rest%20Basics.adoc
