
= Lab 08 : HealthChecks 

In this lab we are going to learn about HealthChecks and how to apply to our use case.
:source-highlighter: coderay


Health checks are used to express the current state of the application in very simple terms: UP or DOWN. The health checks can be used individually, or in combination to Vert.x Web or the event bus.

In Vert.x, HealthChecks module component provides a Vert.x Web handler on which you can register.  The handler computes the final state and returns the result as JSON.


==== Add the following dependency to pom.xml

----

<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-health-check</artifactId>
</dependency>

----

==== Edit sr/main/java/io/vertx/starter/InsultGateway.java 

[code,java]

---- 
import io.vertx.reactivex.ext.healthchecks.*;
import io.vertx.ext.healthchecks.Status;

 HealthCheckHandler healthCheckHandler = HealthCheckHandler.create(vertx)
        .register("server-online", fut -> fut.complete(online ? Status.OK() : Status.KO()));

----

In the above code, we are adding a handler and registering with a name to check the application health

Register following endpoints

==== Edit sr/main/java/io/vertx/starter/InsultGateway.java 

router.get("/api/health/readiness").handler(rc -> rc.response().end("OK"));
    router.get("/api/health/liveness").handler(healthCheckHandler);
    
    
== Deploy to openshift 

1. Checkin your code to github

    git add.
    git commit -m "lab5" 
    git push 

2. Go to OCP console -> pipelines-{userid} project - > builds ->pipelines

3. click on vertx-insult-gateway-pipeline
4. Hit ' Start Pipe line'


Continue to Lab 9 -> https://github.com/rhte-reactive-labs/reactive-pipelines/blob/master/labs/lab09-EventBus.adoc
