
==== Lab instructions


Step 1. Go to following url -> www.opentlc.com/gg/gg.cgi?profile=rhtemgr +
Step 2: Choose a1016(Reactive pipelines using Vert.x) and the key is react +
Step 3: you would presented with id and GUID and instructions to login to developer workstation. Please note them down as we will be using them through out the lab. +




== OpenShift Enivornment details

https://master.{UID}.rhte.opentlc.com/console
userid: provided to you
password: provided to you

Once you login to console, copy the login command on the right corner of the ocp console.

==== SSH to client VM box with the credentials that are provided to you to run OCP commands 

==== Paste the login command you copied (Ex: oc login )

==== Pipelines 

Once you login to your OCP env, please look at below projects

devenv-{userid} +
stageenv-{userid} + 
pipelines-{userid} +

====  pipelines-{userid} PROJECT 

1. Jenkins env is already provisioned +
2. Go to pipelines, you should see 4 pipelines that are already defined and ran successfully.


====  devenv-{userid} PROJECT   - Developement namespace

1. You should all the 4 services(springboot,wildflyswarm,vertx adj,vertx gateway) running in this.  +
2. click on each route url to see everything is working 


====  stageenv-{userid} PROJECT - Test namespace


====  Kickoff build on OpenShift


1. Go back to pipelines-{userid} PROJECT 
2. builds ->pipelines->select 'insult-service-gateway'


While the build is progressing, please continue to lab1




Continue to Lab1 -> https://github.com/rhte-reactive-labs/reactive-pipelines/blob/master/labs/lab01-GettingStarted.adoc



